docs/config/module/README.md, docs/config/module/sink/solrindex.md, docs/config/module/transform/pdfextract.md, examples/bigquery-pdf-to-solrindex.json, pom.xml, src/main/java/com/mercari/solution/FlexPipeline.java, src/main/java/com/mercari/solution/config/SinkConfig.java, src/main/java/com/mercari/solution/config/TransformConfig.java, src/main/java/com/mercari/solution/module/sink/SolrIndexSink.java, src/main/java/com/mercari/solution/module/sink/StorageSink.java, src/main/java/com/mercari/solution/module/sink/fileio/SolrSink.java, src/main/java/com/mercari/solution/module/transform/PDFExtractTransform.java, src/main/java/com/mercari/solution/util/AvroSchemaUtil.java, src/main/java/com/mercari/solution/util/SolrUtil.java, src/main/java/com/mercari/solution/util/XmlUtil.java, src/main/java/com/mercari/solution/util/aws/S3Util.java, src/main/java/com/mercari/solution/util/converter/EntityToSolrDocumentConverter.java, src/main/java/com/mercari/solution/util/converter/RecordToSolrDocumentConverter.java, src/main/java/com/mercari/solution/util/converter/RowToSolrDocumentConverter.java, src/main/java/com/mercari/solution/util/converter/StructToSolrDocumentConverter.java, src/main/java/com/mercari/solution/util/gcp/DatastoreUtil.java, src/main/java/com/mercari/solution/util/gcp/SpannerUtil.java
Add modules for generating Solr index files directly from various data sources.
Added a Sink module `solrindex` for generating Solr index file and a Transform module `pdfextract` for extracting text from PDF files.
=> Add solrindex and pdfextract module.

docs/config/module/README.md, docs/config/module/sink/jdbc.md, docs/config/module/sink/solrindex.md, examples/bigquery-to-jdbc.json, examples/spanner-to-jdbc.json, pom.xml, src/main/java/com/mercari/solution/module/sink/JdbcSink.java, src/main/java/com/mercari/solution/util/converter/ToStatementConverter.java, src/main/java/com/mercari/solution/util/gcp/JdbcUtil.java
Fixed a bug in jdbc's automatic table generation and the insertion of nullable values.
PostgreSQL is also supported.
=> Fix jdbc sink module bug

README.md, docs/config/module/README.md, docs/config/module/sink/text.md, examples/bigquery-to-text.ftl, examples/bigquery-to-text.json, src/main/java/com/mercari/solution/FlexPipeline.java, src/main/java/com/mercari/solution/config/Config.java, src/main/java/com/mercari/solution/config/SinkConfig.java, src/main/java/com/mercari/solution/module/sink/StorageSink.java, src/main/java/com/mercari/solution/module/sink/TextSink.java, src/main/java/com/mercari/solution/module/sink/fileio/TextFileSink.java, src/main/java/com/mercari/solution/util/TemplateFileNaming.java, src/main/java/com/mercari/solution/util/TemplateUtil.java, src/main/java/com/mercari/solution/util/aws/S3Util.java, src/main/java/com/mercari/solution/util/converter/EntityToMapConverter.java, src/main/java/com/mercari/solution/util/converter/MapToCsvConverter.java, src/main/java/com/mercari/solution/util/converter/RecordToMapConverter.java, src/main/java/com/mercari/solution/util/converter/RowToMapConverter.java, src/main/java/com/mercari/solution/util/converter/StructToMapConverter.java, src/main/java/com/mercari/solution/util/gcp/StorageUtil.java
=> Add TextSink module.

docs/config/module/README.md, docs/config/module/transform/crypto.md, docs/config/module/transform/protobuf.md, examples/README.md, examples/spanner-to-decrypt-to-avro.json, examples/spanner-to-protobuf-to-avro.json, pom.xml, src/main/java/com/mercari/solution/FlexPipeline.java, src/main/java/com/mercari/solution/config/SourceConfig.java, src/main/java/com/mercari/solution/config/TransformConfig.java, src/main/java/com/mercari/solution/module/transform/CryptoTransform.java, src/main/java/com/mercari/solution/module/transform/ProtobufTransform.java, src/main/java/com/mercari/solution/util/AvroSchemaUtil.java, src/main/java/com/mercari/solution/util/CryptoUtil.java, src/main/java/com/mercari/solution/util/JsonUtil.java, src/main/java/com/mercari/solution/util/ProtoUtil.java, src/main/java/com/mercari/solution/util/RowSchemaUtil.java, src/main/java/com/mercari/solution/util/TemplateUtil.java, src/main/java/com/mercari/solution/util/converter/JsonToMapConverter.java, src/main/java/com/mercari/solution/util/converter/JsonToRowConverter.java, src/main/java/com/mercari/solution/util/converter/ProtoToEntityConverter.java, src/main/java/com/mercari/solution/util/converter/ProtoToRecordConverter.java, src/main/java/com/mercari/solution/util/converter/ProtoToRowConverter.java, src/main/java/com/mercari/solution/util/converter/ProtoToStructConverter.java, src/main/java/com/mercari/solution/util/converter/StructToRecordConverter.java, src/main/java/com/mercari/solution/util/gcp/DatastoreUtil.java, src/main/java/com/mercari/solution/util/gcp/IAMUtil.java, src/main/java/com/mercari/solution/util/gcp/SpannerUtil.java, src/main/java/com/mercari/solution/util/hashicorp/VaultClient.java
=> Add protobuf and crypto transform modules.

src/main/java/com/mercari/solution/util/ProtoUtil.java, src/main/java/com/mercari/solution/util/converter/ProtoToEntityConverter.java, src/main/java/com/mercari/solution/util/converter/ProtoToRecordConverter.java, src/main/java/com/mercari/solution/util/converter/ProtoToRowConverter.java, src/main/java/com/mercari/solution/util/converter/ProtoToStructConverter.java, src/test/java/com/mercari/solution/util/converter/ProtoToEntityConverterTest.java, src/test/java/com/mercari/solution/util/converter/ProtoToRecordConverterTest.java, src/test/java/com/mercari/solution/util/converter/ProtoToRowConverterTest.java, src/test/java/com/mercari/solution/util/converter/ProtoToStructConverterTest.java
=> Add ProtoToRecord and ProtoToEntity unit test code, and bugfix.

docs/config/module/sink/spanner.md, src/main/java/com/mercari/solution/module/sink/SpannerSink.java
=> Add SpannerSink parameter: failFast, revertNodeCount, rebalancingMinite.

docs/config/module/transform/filtercondition.md, docs/config/module/transform/partition.md, examples/avro-to-partition-to-spanner.json, src/main/java/com/mercari/solution/module/transform/PartitionTransform.java, src/main/java/com/mercari/solution/util/Filter.java, src/main/java/com/mercari/solution/util/converter/StructToCsvConverter.java, src/main/java/com/mercari/solution/util/schema/AvroSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/EntitySchemaUtil.java, src/main/java/com/mercari/solution/util/schema/RowSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/StructSchemaUtil.java, src/test/java/com/mercari/solution/module/transform/PartitionTransformTest.java, src/test/java/com/mercari/solution/util/FilterTest.java
Add partition transform module  that splits a data collection into separate data collections based on conditions.
=> Add PartitionTransform

docs/config/module/README.md
Fixed omission of reflection in README.
=> Add partition module ref on README.md

docs/config/module/README.md, docs/config/module/sink/pubsub.md, examples/bigquery-to-pubsub.json, src/main/java/com/mercari/solution/module/sink/PubSubSink.java, src/main/java/com/mercari/solution/util/converter/EntityToJsonConverter.java, src/main/java/com/mercari/solution/util/converter/RecordToJsonConverter.java, src/main/java/com/mercari/solution/util/converter/RowToJsonConverter.java, src/main/java/com/mercari/solution/util/converter/StructToJsonConverter.java, src/main/java/com/mercari/solution/util/schema/AvroSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/EntitySchemaUtil.java, src/test/java/com/mercari/solution/TestDatum.java, src/test/java/com/mercari/solution/util/converter/EntityToJsonConverterTest.java, src/test/java/com/mercari/solution/util/converter/RecordToJsonConverterTest.java, src/test/java/com/mercari/solution/util/converter/RowToJsonConverterTest.java, src/test/java/com/mercari/solution/util/converter/StructToJsonConverterTest.java
Add PubSubSink.
Publish a message in JSON or Avro format to a specified PubSub topic.
doc: https://github.com/mercari/DataflowTemplate/blob/master/docs/config/module/sink/pubsub.md
=> add pubsub sink.

docs/config/module/source/pubsub.md, examples/README.md, examples/pubsub-to-beamsql-to-pubsub.json, src/main/java/com/mercari/solution/module/sink/PubSubSink.java, src/main/java/com/mercari/solution/module/source/PubSubSource.java, src/main/java/com/mercari/solution/util/converter/JsonToRecordConverter.java, src/main/java/com/mercari/solution/util/converter/JsonToRowConverter.java, src/test/java/com/mercari/solution/util/converter/JsonToRecordConverterTest.java, src/test/java/com/mercari/solution/util/converter/JsonToRowConverterTest.java
* Added functionality to accept data in JSON format from PubSub source module.
* Fixed a bug that caused an error when idAttribute was not specified in PubSub sink module.
=> Support json format pubsub source

docs/config/module/transform/filter.md, examples/avro-to-filter-to-avro.json, src/main/java/com/mercari/solution/FlexPipeline.java, src/main/java/com/mercari/solution/module/transform/FilterTransform.java, src/main/java/com/mercari/solution/module/transform/PDFExtractTransform.java, src/main/java/com/mercari/solution/util/converter/StructToRowConverter.java, src/main/java/com/mercari/solution/util/schema/AvroSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/EntitySchemaUtil.java, src/main/java/com/mercari/solution/util/schema/RowSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/StructSchemaUtil.java, src/test/java/com/mercari/solution/TestDatum.java, src/test/java/com/mercari/solution/module/transform/FilterTransformTest.java, src/test/java/com/mercari/solution/util/schema/AvroSchemaUtilTest.java, src/test/java/com/mercari/solution/util/schema/EntitySchemaUtilTest.java, src/test/java/com/mercari/solution/util/schema/RowSchemaUtilTest.java, src/test/java/com/mercari/solution/util/schema/StructSchemaUtilTest.java
Added a Transform module that allows you to filter records that match specified criteria.
You can specify not only the rows, but also the list of columns you want to pass through.
Columns can be specified even if they are nested in a structure or array.
=> Add filter transform module.

README.md, docs/config/module/README.md, docs/config/module/transform/beamsql.md, docs/config/module/transform/filter.md, examples/README.md
The REST API execution of flextemplate was outdated, so it was modified to launch using the appropriate API.
=> Update README description about launching flexTemplate

README.md, docs/deploy/README.md, docs/exec/README.md
=> Add description to run dataflow job in streaming mode

docs/config/module/README.md, docs/config/module/source/pubsub.md, docs/config/module/transform/eventtime.md, examples/pubsub-to-beamsql-to-pubsub.json, src/main/java/com/mercari/solution/config/SourceConfig.java, src/main/java/com/mercari/solution/module/source/PubSubSource.java, src/main/java/com/mercari/solution/module/transform/EventTimeTransform.java, src/main/java/com/mercari/solution/util/gcp/PubSubUtil.java, src/main/java/com/mercari/solution/util/schema/AvroSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/RowSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/StructSchemaUtil.java, src/test/java/com/mercari/solution/module/transform/EventTimeTransformTest.java
If a message fails to be parsed or deserialized in the PubSub Source module, the message will be sent to the Deadletter topic if one is set in the received topic.
In addition, the event time extraction in the PubSub module has been separated into a separate module called EventtimeTransform.
=> support pubsub source dead letter.

docs/config/module/README.md, docs/config/module/transform/bandit.md, examples/README.md, examples/bigquery-to-bandit-to-bigquery.json, examples/pubsub-to-bandit-to-pubsub-bigquery.json, src/main/java/com/mercari/solution/module/transform/BanditTransform.java, src/main/java/com/mercari/solution/util/schema/AvroSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/EntitySchemaUtil.java, src/main/java/com/mercari/solution/util/schema/RowSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/StructSchemaUtil.java, src/test/java/com/mercari/solution/module/transform/BanditTransformTest.java
Added a Transform module that runs a simple multi-armed bandit algorithm.
=> add bandit transform module.

docs/config/module/README.md, docs/config/module/transform/bar.md, examples/pubsub-to-bar-to-bigquery.json, src/main/java/com/mercari/solution/module/transform/BarTransform.java, src/test/java/com/mercari/solution/module/transform/BarTransformTest.java
Added BarTransform to generate financial bars from transaction data.
=> Add bar transform.

src/main/java/com/mercari/solution/module/sink/StorageSink.java, src/main/java/com/mercari/solution/module/source/StorageSource.java, src/main/java/com/mercari/solution/util/DateTimeUtil.java, src/main/java/com/mercari/solution/util/converter/CsvToRecordConverter.java, src/main/java/com/mercari/solution/util/converter/JsonToRecordConverter.java, src/main/java/com/mercari/solution/util/converter/RecordToSolrDocumentConverter.java, src/main/java/com/mercari/solution/util/converter/RowToRecordConverter.java, src/main/java/com/mercari/solution/util/converter/TableRowToRecordConverter.java, src/main/java/com/mercari/solution/util/schema/AvroSchemaUtil.java, src/test/java/com/mercari/solution/debug/AvroViewer.java, src/test/java/com/mercari/solution/util/DateTimeUtilTest.java, src/test/java/com/mercari/solution/util/schema/AvroSchemaUtilTest.java
* Unified date/time related convenience functions into a utility class.
* Added logic to estimate schema of JSON at runtime. (not usable yet)
=> Support auto detect json schema

.gitignore, docs/config/module/README.md, docs/config/module/sink/debug.md, src/main/java/com/mercari/solution/module/sink/DebugSink.java, src/main/java/com/mercari/solution/module/transform/WindowTransform.java, src/main/java/com/mercari/solution/util/converter/RecordToEntityConverter.java, src/main/java/com/mercari/solution/util/converter/RowToEntityConverter.java, src/main/java/com/mercari/solution/util/schema/AvroSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/EntitySchemaUtil.java, src/main/java/com/mercari/solution/util/schema/RowSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/StructSchemaUtil.java, src/test/java/com/mercari/solution/debug/DebugPipeline.java
* Add debug pipeline and sink for development
* Support window transform module timestampCombiner option.
* Add getAsDecimal each data type utils.
=> Add debug pipeline utility

docs/config/module/README.md, docs/config/module/transform/javascript.md, src/main/java/com/mercari/solution/module/transform/JavaScriptTransform.java, src/main/java/com/mercari/solution/util/OptionUtil.java, src/main/java/com/mercari/solution/util/converter/RowToMapConverter.java, src/test/java/com/mercari/solution/module/transform/JavaScriptTransformTest.java, src/test/resources/module/transform/javascript/script.js
Added a javascript transform module that allows you to process records by a script defined in JavaScript and save the result in a specified field.
=> add javascript transform module.

docs/config/module/README.md, docs/config/module/sink/bigtable.md, examples/bigquery-to-bigtable.json, src/main/java/com/mercari/solution/module/sink/BigtableSink.java, src/main/java/com/mercari/solution/util/DateTimeUtil.java, src/main/java/com/mercari/solution/util/TemplateUtil.java, src/main/java/com/mercari/solution/util/converter/DataTypeTransform.java, src/main/java/com/mercari/solution/util/converter/EntityToBigtableConverter.java, src/main/java/com/mercari/solution/util/converter/RowToBigtableConverter.java, src/main/java/com/mercari/solution/util/converter/StructToBigtableConverter.java, src/main/java/com/mercari/solution/util/schema/AvroSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/EntitySchemaUtil.java, src/main/java/com/mercari/solution/util/schema/RowSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/StructSchemaUtil.java
Add sink module to insert record to Cloud Bigtable.
=> Add bigtable sink

pom.xml, src/main/java/com/mercari/solution/module/transform/WindowTransform.java, src/main/java/com/mercari/solution/util/converter/RecordToMapConverter.java, src/main/java/com/mercari/solution/util/schema/AvroSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/RowSchemaUtil.java
* beam sdk version up 2.29 -> 2.30
* support schema util function `merge` array field
* small bug fix
=> Beam version up

docs/config/module/sink/bigtable.md, docs/config/module/sink/spanner.md, src/main/java/com/mercari/solution/module/sink/BigtableSink.java
The values of columnFamily and columnQualifier in Bigtable Sink can be specified dynamically according to the data values by using FreeMarker, a TemplateEngine.
=> support bigtable sink template columnQualifier

docs/config/module/sink/datastore.md, src/main/java/com/mercari/solution/module/sink/DatastoreSink.java, src/main/java/com/mercari/solution/module/transform/BeamSQLTransform.java, src/main/java/com/mercari/solution/util/converter/RecordToEntityConverter.java, src/main/java/com/mercari/solution/util/converter/RowToEntityConverter.java, src/main/java/com/mercari/solution/util/converter/StructToEntityConverter.java, src/main/java/com/mercari/solution/util/schema/EntitySchemaUtil.java
* Support datastore sink template key (like bigtable sink rowKeyTemplate)
* bugfix EntitySchemaUtil.getTimestamp
* bugfix BeamSQLTransform for duplication build-in udf function (JSON_EXTRACT)
=> Support datastore sink template key

Dockerfile, README.md, docs/config/README.md, pom.xml, src/main/java/com/mercari/solution/FlexPipeline.java, src/main/java/com/mercari/solution/config/SinkConfig.java, src/main/java/com/mercari/solution/config/SourceConfig.java, src/main/java/com/mercari/solution/config/TransformConfig.java, src/main/java/com/mercari/solution/module/transform/BufferTransform.java, src/main/java/com/mercari/solution/util/converter/RecordToTableRowConverter.java, src/main/java/com/mercari/solution/util/converter/ResultSetToRecordConverter.java, src/main/java/com/mercari/solution/util/converter/RowToTableRowConverter.java, src/main/java/com/mercari/solution/util/converter/StructToTableRowConverter.java, src/main/java/com/mercari/solution/util/gcp/BigQueryUtil.java, src/main/java/com/mercari/solution/util/gcp/PubSubUtil.java, src/main/java/com/mercari/solution/util/gcp/StorageUtil.java, src/main/java/com/mercari/solution/util/schema/AvroSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/RowSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/StructSchemaUtil.java, src/test/java/com/mercari/solution/module/transform/BanditTransformTest.java
* Add skip setting for all module
* Update beam sdk to 2.31
* Bugfix BigQuery sink for nested records file loads
* Support decimal type for JdbcSource
* Add BufferTransform module
=> Add buffer transform

docs/config/module/source/pubsub.md, src/main/java/com/mercari/solution/module/source/PubSubSource.java, src/main/java/com/mercari/solution/util/converter/JsonToRecordConverter.java, src/main/java/com/mercari/solution/util/converter/JsonToRowConverter.java, src/main/java/com/mercari/solution/util/converter/PubSubToRecordConverter.java, src/main/java/com/mercari/solution/util/converter/RecordToTableRowConverter.java, src/main/java/com/mercari/solution/util/converter/RowToTableRowConverter.java, src/main/java/com/mercari/solution/util/converter/TableRowToRecordConverter.java, src/test/java/com/mercari/solution/util/converter/JsonToRecordConverterTest.java, src/test/java/com/mercari/solution/util/converter/JsonToRowConverterTest.java, src/test/java/com/mercari/solution/util/converter/TableRowToRecordConverterTest.java
* Support `message` format for PubSubSource
* Support handling unnecessary json fields as error
* Bugfix for bytes and map type conversion for ToTableRow
=> Support flexible pubsub source

docs/config/module/sink/datastore.md, docs/config/module/transform/filter.md, docs/config/module/transform/filtercondition.md, examples/avro-to-filter-to-avro.json, pom_solr.xml, src/main/java/com/mercari/solution/module/sink/DatastoreSink.java, src/main/java/com/mercari/solution/module/transform/FilterTransform.java, src/main/java/com/mercari/solution/util/DateTimeUtil.java, src/main/java/com/mercari/solution/util/Filter.java, src/main/java/com/mercari/solution/util/OptionUtil.java, src/main/java/com/mercari/solution/util/converter/RecordToEntityConverter.java, src/main/java/com/mercari/solution/util/converter/RowToEntityConverter.java, src/main/java/com/mercari/solution/util/converter/RowToMapConverter.java, src/main/java/com/mercari/solution/util/converter/StructToEntityConverter.java, src/main/java/com/mercari/solution/util/gcp/VertexAIUtil.java, src/main/java/com/mercari/solution/util/schema/AvroSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/EntitySchemaUtil.java, src/main/java/com/mercari/solution/util/schema/RowSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/StructSchemaUtil.java, src/test/java/com/mercari/solution/util/FilterTest.java
* Add jts library to support solr heatmap
* Support excludeFromIndexFields option for datastore sink module
* Support date and timestamp filter condition and rename function for filter transform module
* bugfix for template variables inspection from Row
=> Support solr heatmap

src/main/java/com/mercari/solution/util/schema/EntitySchemaUtil.java
bugfix datastore sink module (from Entity)
=> bugfix EntitySchemaUtil.convertBuilder

docs/config/module/source/datastore.md, examples/datastore-to-delete.json, src/main/java/com/mercari/solution/module/sink/BigQuerySink.java, src/main/java/com/mercari/solution/module/source/DatastoreSource.java, src/main/java/com/mercari/solution/util/converter/EntityToRecordConverter.java, src/main/java/com/mercari/solution/util/converter/EntityToRowConverter.java, src/main/java/com/mercari/solution/util/converter/EntityToTableRowConverter.java
Bugfix for datastore source (support withKey parameter to read `__key__` field)
=> bugfix datastore source with key.

docs/config/module/source/spanner.md, pom.xml, src/main/java/com/mercari/solution/module/sink/StorageSink.java, src/main/java/com/mercari/solution/module/source/SpannerSource.java
* support priority parameter for spanner source
* bugfix prefix parameter for storage sink
* beam sdk version up to 2.32
=> Support spanner source priority

pom.xml, pom_secure.xml, src/main/java/com/mercari/solution/module/sink/fileio/SolrSink.java, src/main/java/com/mercari/solution/util/converter/RecordToSolrDocumentConverter.java, src/main/java/com/mercari/solution/util/schema/SolrSchemaUtil.java
* Provide a more secure configuration pom file (pom_secure.xml).
* Minor bug fixes around SolrIndexSink
=> Reorganize unnecessary libraries.

pom.xml, pom_secure.xml
Also remove dependencies of dependent libraries
=> update dependency log4j2

pom.xml, pom_secure.xml
Please read the CLA carefully before submitting your contribution to Mercari.
Under any circumstances, by submitting your contribution, you are deemed to accept and agree to be bound by the terms and conditions of the CLA.
https://www.mercari.com/cla/
Hi. Thanks for this useful repository!!
Update log4j version
ref: https://www.cyberkendra.com/2021/12/worst-log4j-rce-zeroday-dropped-on.html
=> Update log4j 2.16.0

pom.xml, pom_secure.xml, pom_solr.xml
=> update log4j2 2.17

Dockerfile, README.md, docs/config/module/README.md, docs/config/module/source/websocket.md, docs/config/module/transform/beamsql.md, docs/config/module/transform/beamsqludf.md, docs/config/module/transform/window.md, pom.xml, src/main/java/com/mercari/solution/FlexPipeline.java, src/main/java/com/mercari/solution/config/Config.java, src/main/java/com/mercari/solution/config/SinkConfig.java, src/main/java/com/mercari/solution/config/SourceConfig.java, src/main/java/com/mercari/solution/config/TransformConfig.java, src/main/java/com/mercari/solution/module/source/BigQuerySource.java, src/main/java/com/mercari/solution/module/source/WebSocketSource.java, src/main/java/com/mercari/solution/module/transform/BeamSQLTransform.java, src/main/java/com/mercari/solution/module/transform/WindowTransform.java, src/main/java/com/mercari/solution/util/converter/JsonToRecordConverter.java, src/main/java/com/mercari/solution/util/converter/JsonToRowConverter.java, src/main/java/com/mercari/solution/util/converter/RowToRecordConverter.java, src/main/java/com/mercari/solution/util/sql/udf/AggregateFunctions.java, src/main/java/com/mercari/solution/util/sql/udf/ArrayFunctions.java, src/main/java/com/mercari/solution/util/sql/udf/MathFunctions.java, src/test/java/com/mercari/solution/module/transform/BeamSQLTransformTest.java, src/test/java/com/mercari/solution/module/transform/WindowTransformTest.java
* Update beam sdk to 2.35.0
* Add trigger settings for window transform module
* Add original UDFs and planner option for beamsql transform module
* Add websocket source module (experimental)
=> Update beam sdk 2.35.0

docs/config/module/README.md, docs/config/module/transform/union.md, examples/pubsub-to-union-to-bigquery.json, pom.xml, src/main/java/com/mercari/solution/module/transform/UnionTransform.java, src/main/java/com/mercari/solution/util/schema/AvroSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/EntitySchemaUtil.java, src/main/java/com/mercari/solution/util/schema/RowSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/StructSchemaUtil.java, src/test/java/com/mercari/solution/module/transform/UnionTransformTest.java
* Add union module
* Update postgresql connector version
=> Add union transform module

Dockerfile, cloudbuild/branch.yaml, cloudbuild/tag.yaml
Add build files for cloud build
=> Add cloudbuild yaml

docs/config/module/sink/datastore.md, docs/config/module/source/drivefile.md, examples/drivefile-to-copyfile.json, src/main/java/com/mercari/solution/module/sink/DatastoreSink.java, src/main/java/com/mercari/solution/module/source/DriveFileSource.java, src/main/java/com/mercari/solution/util/gcp/DriveUtil.java, src/main/java/com/mercari/solution/util/gcp/StorageUtil.java
* Add drivefile source module
* add enableRampupThrottling option for datastore source module (and change the default to false)
=> Add drivefile source

README.md, docs/config/module/README.md, docs/config/module/sink/copyfile.md, docs/config/module/sink/datastore.md, docs/config/module/source/drivefile.md, examples/README.md, examples/drivefile-to-copyfile.json, pom.xml, src/main/java/com/mercari/solution/module/sink/CopyFileSink.java, src/main/java/com/mercari/solution/module/sink/DatastoreSink.java, src/main/java/com/mercari/solution/module/source/DriveFileSource.java, src/main/java/com/mercari/solution/util/aws/S3Util.java, src/main/java/com/mercari/solution/util/gcp/DriveUtil.java, src/main/java/com/mercari/solution/util/gcp/StorageUtil.java
* Add copyfile sink module
* Update Beam SDK to 2.37 and update dependencies
=> Add copyfile sink

src/main/java/com/mercari/solution/module/transform/BeamSQLTransform.java, src/main/java/com/mercari/solution/util/sql/udf/AggregateFunctions.java, src/test/java/com/mercari/solution/module/transform/BeamSQLTransformTest.java
Please read the CLA carefully before submitting your contribution to Mercari.
Under any circumstances, by submitting your contribution, you are deemed to accept and agree to be bound by the terms and conditions of the CLA.
https://www.mercari.com/cla/
Thanks for the great repo! 
I've found some unregistered UDAFs for distinct aggregations which seem to be working ok, was there a reason to exclude them? I've also added a few count distinct functions which can be useful in case it's ok!
=> Add distinct agg udafs

docs/config/module/source/jdbc.md, examples/jdbc-table-to-spanner.json, examples/jdbc-to-bigquery-with-prep-param-queries.json, pom.xml, src/main/java/com/mercari/solution/module/source/JdbcSource.java, src/main/java/com/mercari/solution/module/transform/ProtobufTransform.java, src/main/java/com/mercari/solution/util/DateTimeUtil.java, src/main/java/com/mercari/solution/util/converter/RecordToMutationConverter.java, src/main/java/com/mercari/solution/util/converter/RecordToRowConverter.java, src/main/java/com/mercari/solution/util/converter/ResultSetToRecordConverter.java, src/main/java/com/mercari/solution/util/gcp/JdbcUtil.java, src/main/java/com/mercari/solution/util/gcp/SecretManagerUtil.java, src/main/java/com/mercari/solution/util/gcp/SpannerUtil.java, src/main/java/com/mercari/solution/util/schema/AvroSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/StructSchemaUtil.java, src/test/java/com/mercari/solution/util/DateTimeUtilTest.java, src/test/java/com/mercari/solution/util/converter/RecordToRowConverterTest.java, src/test/java/com/mercari/solution/util/gcp/JdbcUtilTest.java, src/test/java/com/mercari/solution/util/gcp/SecretManagerUtilTest.java
* Support JDBC table seek read
* Support JDBC array, numeric type (#60)
* Enable assignment of `user` and `password` by secret manager (#60)
=> Enhance jdbc

Dockerfile, pom.xml, src/main/java/com/mercari/solution/util/gcp/BigQueryUtil.java
=> Update tag 0.8.0

docs/config/module/sink/pubsub.md, examples/README.md, examples/dummy-to-pubsub.json, src/main/java/com/mercari/solution/module/sink/PubSubSink.java
* support ordering key for pubsub sink module 
ref: #71
=> Support pubsub sink ordering keys

src/main/java/com/mercari/solution/module/sink/BigQuerySink.java, src/main/java/com/mercari/solution/util/pipeline/Merge.java
* fix inappropriate opsion for bigquery sink module default autoSharding when using batch file_loads method 
* fix merge for avro record
=> Bugfix bigquery sink batch

docs/config/module/README.md, docs/config/module/transform/aggregation.md, docs/config/module/transform/bar.md, examples/README.md, examples/bigquery-to-aggregation-to-bigquery.json, examples/pubsub-to-aggregation-to-pubsub.json, src/main/java/com/mercari/solution/module/DataType.java, src/main/java/com/mercari/solution/module/transform/AggregationTransform.java, src/main/java/com/mercari/solution/module/transform/PDFExtractTransform.java, src/main/java/com/mercari/solution/util/pipeline/aggregation/Accumulator.java, src/main/java/com/mercari/solution/util/pipeline/aggregation/Aggregator.java, src/main/java/com/mercari/solution/util/pipeline/aggregation/Aggregators.java, src/main/java/com/mercari/solution/util/pipeline/aggregation/ArgMax.java, src/main/java/com/mercari/solution/util/pipeline/aggregation/Avg.java, src/main/java/com/mercari/solution/util/pipeline/aggregation/Count.java, src/main/java/com/mercari/solution/util/pipeline/aggregation/Last.java, src/main/java/com/mercari/solution/util/pipeline/aggregation/Max.java, src/main/java/com/mercari/solution/util/pipeline/aggregation/Std.java, src/main/java/com/mercari/solution/util/pipeline/aggregation/Sum.java, src/main/java/com/mercari/solution/util/pipeline/union/Union.java, src/main/java/com/mercari/solution/util/pipeline/union/UnionCoder.java, src/main/java/com/mercari/solution/util/pipeline/union/UnionValue.java, src/main/java/com/mercari/solution/util/schema/AvroSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/DocumentSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/EntitySchemaUtil.java, src/main/java/com/mercari/solution/util/schema/RowSchemaUtil.java, src/main/java/com/mercari/solution/util/schema/SchemaUtil.java, src/main/java/com/mercari/solution/util/schema/StructSchemaUtil.java, src/test/java/com/mercari/solution/module/transform/AggregationTransformTest.java
* Add aggregation transform module
* Add union transform(inner use)
* Remove not using data type(text, bigtablemutation)
=> add aggregation transform module

README.md
Hi, thanks for the great project!
I added a missing double quotation in the README.md file that I noticed while following the command.
Please take a look at this when you have time!
> Please read the CLA carefully before submitting your contribution to Mercari.
Under any circumstances, by submitting your contribution, you are deemed to accept and agree to be bound by the terms and conditions of the CLA.
https://www.mercari.com/cla/
↑Confirmed.
=> Update README.md: add missing double quotation

src/main/java/com/mercari/solution/util/converter/RecordToProtoConverter.java
Hi, I have a suggestion for enhancing the error log when converting schema to proto.
The current code simply throws a NullPointerException along with a stack trace when the message descriptor's field and the schema's field differ. I suggest adding an informative log to make it more user-friendly.
Here is an example where the BigQuery table has a field named `word`, and the protobuf message descriptor defines a field called `word_`.
```
Exception in thread "main" org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.NullPointerException: Cannot invoke "org.apache.avro.Schema$Field.schema()" because the return value of "org.apache.avro.Schema.getField(String)" is null
at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:377)
at …
```
=> Update: add error log when converting schema to proto

src/main/java/com/mercari/solution/module/sink/JdbcSink.java, src/main/java/com/mercari/solution/module/source/JdbcSource.java, src/main/java/com/mercari/solution/util/gcp/JdbcUtil.java
This pull request fixes pooled JDBC connections leaks.
=> Clean up leaked JDBC connections

src/main/java/com/mercari/solution/util/converter/ResultSetToRecordConverter.java, src/main/java/com/mercari/solution/util/converter/ToStatementConverter.java, src/main/java/com/mercari/solution/util/schema/AvroSchemaUtil.java, src/main/java/com/mercari/solution/util/sql/stmt/PreparedStatementTemplate.java, src/test/java/com/mercari/solution/util/TemplateUtilTest.java
Issue: #101
* add uuid type for avro record
* suppor uuid sql type for jdbc source and sink module
=> support uuid type for jdbc source and sink module

src/main/java/com/mercari/solution/module/sink/JdbcSink.java, src/main/java/com/mercari/solution/module/sink/fileio/H2Sink.java, src/main/java/com/mercari/solution/util/schema/converter/ToStatementConverter.java
=> move ToStatementConverter.java

docs/config/module/sink/jdbc.md, examples/README.md, examples/bigquery-to-alloydb.yaml, pom.xml, src/main/java/com/mercari/solution/MPipeline.java, src/main/java/com/mercari/solution/config/Config.java, src/main/java/com/mercari/solution/config/ModuleConfig.java, src/main/java/com/mercari/solution/config/TransformConfig.java, src/main/java/com/mercari/solution/module/MErrorHandler.java, src/main/java/com/mercari/solution/module/Module.java, src/main/java/com/mercari/solution/module/sink/DatastoreSink.java, src/main/java/com/mercari/solution/module/sink/FirestoreSink.java, src/main/java/com/mercari/solution/module/source/JdbcSource.java, src/main/java/com/mercari/solution/util/gcp/JdbcUtil.java
* update dependencies
* refactor config processing
* support error handler for datastore, firestore sinks
* fix jdbc source to get schema
=> Refactor configs
